# Simple workflow for syncing content to another repo
name: Sync content to aggregate repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:Star-Academy/codestar1403-frontend-assessment.git
          BRANCH: main
          FOLDER: .
          TARGET_DIR: Maze/design/
          MESSAGE: 'Update maze: {msg}'
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
          
